# syntax=docker/dockerfile:1
#
# Production image for Next.js 16 using `output: "standalone"`.
# Multi-stage: deps -> builder -> runner. The final image runs the traced
# standalone server as a non-root user and contains no dev dependencies.

# ---- Base ---------------------------------------------------------------
FROM node:24-alpine AS base
# libc6-compat: some npm packages expect glibc symbols on musl-based Alpine.
RUN apk add --no-cache libc6-compat
WORKDIR /app

# ---- Dependencies -------------------------------------------------------
# Isolated so it only re-runs when the lockfile changes. The BuildKit cache
# mount keeps npm's download cache warm across builds.
FROM base AS deps
COPY package.json package-lock.json ./
RUN --mount=type=cache,target=/root/.npm \
    npm ci

# ---- Builder ------------------------------------------------------------
# No DATABASE_URL / secrets needed: every DB-backed page is force-dynamic and
# there are no NEXT_PUBLIC_* vars, so the build never touches Postgres.
FROM base AS builder
ENV NEXT_TELEMETRY_DISABLED=1
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

# ---- Runner -------------------------------------------------------------
FROM base AS runner
ENV NODE_ENV=production \
    NEXT_TELEMETRY_DISABLED=1 \
    PORT=3000 \
    HOSTNAME=0.0.0.0

RUN addgroup --system --gid 1001 nodejs \
 && adduser --system --uid 1001 nextjs

# public assets are not part of the standalone bundle — copy them explicitly.
COPY --from=builder /app/public ./public

# Standalone server + its minimal traced node_modules (already production-only).
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
# Static assets (hashed JS/CSS) are also excluded from standalone — copy them.
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs
EXPOSE 3000

# server.js is generated by `output: "standalone"` and listens on $HOSTNAME:$PORT.
CMD ["node", "server.js"]
